name: CD Pipeline

on:
    push:
        branches:
        - main

env:
    PROJECT_ID: ${{ vars.GOOGLE_CLOUD_PROJECT }}
    REGION: europe-west4
    BUCKET: ${{ vars.GOOGLE_CLOUD_BUCKET }}

jobs:
   build-and-deploy:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

       - name: Docker login to GitHub
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}

       - name: Configure Docker for GCR
         run: gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev

       - name: Set up Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v1
         with:
           project_id: ${{ env.PROJECT_ID }}

       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v2
         with:
           credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

       - name: Build an Push Docker image
         run: |
          docker build -t ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/features-repo/features-builder:latest -f features_build.Dockerfile .
          docker push ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/features-repo/features-builder:latest

       - name: Create and Run Vertex AI job
         run: |
          gcloud ai custom-jobs create \
           --region=${{env.REGION}} \
           --project=${{env.PROJECT_ID}} \
           --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,container-image-uri=${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/features-repo/features-builder:latest \
           --display-name=features-builder