name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-list-and-build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest black isort pylint

        - name: Check formatting with Black
          run: black --check .

        - name: Check import sorting with isort
          run: isort --check-only --diff .

        - name: Run tests
          run: pytest tests/ -v

        - name: Build docker image
          run: docker build -t features-builder -f features_build.Dockerfile .